const d = () => {
    try{
        let a=0;
        // console.log(program)
        console.log("Program ran successfully")
        return
    }
    catch(error){
        console.log("This is an error")
        console.log(p)
    }
    finally {
        console.log("I am Dev Vaghasiya")
    }
}

d()